export const BIRDS_LOADED = 'BIRDS_LOADED'
export const TEXT_CHANGE = 'TEXT_CHANGE'
export const ADD_BIRD_TO_MY_BIRDS = 'ADD_BIRD_TO_MY_BIRDS'
export const SET_MY_BIRDS = 'SET_MY_BIRDS'
export const REMOVE_BIRD_FROM_MY_BIRDS = 'REMOVE_BIRD_FROM_MY_BIRDS'
export const LOADING = 'LOADING'
export const LOADED = 'LOADED'
export const ADD_PIN = 'ADD_PIN'
